name: Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only allow auto-merge if the PR was created by the scala-steward bot
    if: github.actor == 'github-actions[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          # Use PAT to ensure the merge has the necessary permissions
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PAT }}